version: 0.2

env:
  shell: bash
  variables:
    CI: true
    PIP_DISABLE_PIP_VERSION_CHECK: true
    PIP_QUIET: true

phases:
  install:
    runtime-versions:
      python: 3.8
      nodejs: 14
    commands:
      - aws codeartifact login --tool pip --repository $CODEARTIFACT_PYPI_REPO --domain $CODEARTIFACT_DOMAIN --domain-owner $SHARED_SERVICES_ACCOUNT_ID
      - pip install pipx==$PIPX_PACKAGE_VERSION
      # Add pipx binaries to path
      - export PATH="$PATH:/root/.local/bin"
      - pipx install dgx-devops-deploy-library==$DEPLOY_LIBRARY_PACKAGE_VERSION
      - dgx-deploy aws codeartifact npm-login
        --repository $CODEARTIFACT_NPM_REPO
        --domain $CODEARTIFACT_DOMAIN
        --domain-owner $SHARED_SERVICES_ACCOUNT_ID
        --ssm-parameter-path /$PROJECT_OWNER/shared/codebuild/codeartifact/npmlogin
  build:
    commands:
      - dgx-deploy deploy-notify --status started
      - dgx-deploy dataload deploy
  post_build:
    commands:
      - dgx-deploy deploy-notify --use-codebuild-env-var
